"use client";

import React, { useState } from "react";
import { useBusinessContext } from "@/context/BusinessContext";
import { FranchiseModal } from "@/components/dashboard/FranchiseModal";
import toast from "react-hot-toast";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import {
  Building2,
  Store,
  Plus,
  Search,
  MapPin,
  User,
  Mail,
  Phone,
  ArrowRight,
  Copy,
  Send,
  Trash2,
  AlertTriangle,
  BarChart3,
  TrendingUp,
  Check,
  ShieldAlert,
} from "lucide-react";

const PIE_COLORS = ["#f59e0b", "#10b981", "#3b82f6", "#8b5cf6", "#ec4899"];

function FranchiseAnalyticsView({ franchises }) {
  const chartData = franchises.map((f) => ({
    name: f.name.replace("Thikana Outlet - ", ""),
    revenue: f.monthlyRevenue,
    orders: f.ordersToday,
  }));

  const pieData = franchises.map((f) => ({
    name: f.name.replace("Thikana Outlet - ", ""),
    value: f.monthlyRevenue,
  }));

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Comparative Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Revenue Bar Chart */}
        <div className="lg:col-span-2 bg-white dark:bg-[#1A1A1A] p-6 rounded-3xl border border-[#E5E0D8] dark:border-white/10 shadow-xs">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="font-extrabold text-base text-[#1A1A1A] dark:text-white flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-amber-500" /> Multi-Outlet Revenue Comparison
              </h3>
              <p className="text-xs text-gray-500">Gross monthly revenue generated by each child outlet</p>
            </div>
            <span className="text-[10px] font-extrabold px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
              Live Recharts
            </span>
          </div>

          <div className="h-64 w-full pt-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" opacity={0.1} />
                <XAxis dataKey="name" stroke="#888888" fontSize={11} tickLine={false} />
                <YAxis
                  stroke="#888888"
                  fontSize={11}
                  tickLine={false}
                  tickFormatter={(v) => `₹${(v / 1000).toFixed(0)}k`}
                />
                <Tooltip
                  formatter={(value) => [`₹${value.toLocaleString("en-IN")}`, "Monthly Revenue"]}
                  contentStyle={{ backgroundColor: "#1C1C1C", borderRadius: "12px", border: "none", color: "#fff" }}
                />
                <Bar dataKey="revenue" fill="#f59e0b" radius={[8, 8, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Order Share Pie Chart */}
        <div className="bg-white dark:bg-[#1A1A1A] p-6 rounded-3xl border border-[#E5E0D8] dark:border-white/10 shadow-xs flex flex-col justify-between">
          <div>
            <h3 className="font-extrabold text-base text-[#1A1A1A] dark:text-white mb-1">
              Revenue Share Distribution
            </h3>
            <p className="text-xs text-gray-500 mb-4">Proportionate breakdown across outlets</p>

            <div className="h-44 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    innerRadius={45}
                    outerRadius={70}
                    paddingAngle={4}
                    dataKey="value"
                  >
                    {pieData.map((_, index) => (
                      <Cell key={`cell-${index}`} fill={PIE_COLORS[index % PIE_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(val) => `₹${val.toLocaleString("en-IN")}`} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="space-y-1.5 pt-2 border-t border-gray-100 dark:border-white/10">
            {pieData.map((item, idx) => (
              <div key={idx} className="flex items-center justify-between text-xs font-bold">
                <div className="flex items-center gap-2">
                  <div
                    className="w-2.5 h-2.5 rounded-full"
                    style={{ backgroundColor: PIE_COLORS[idx % PIE_COLORS.length] }}
                  />
                  <span className="text-gray-700 dark:text-gray-300 truncate max-w-[120px]">{item.name}</span>
                </div>
                <span className="text-amber-600 dark:text-amber-400">
                  ₹{(item.value / 1000).toFixed(0)}k
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export function FranchisesTab() {
  const {
    franchises = [],
    userData,
    isHeadquarters,
    isFranchise,
    switchToFranchise,
    addFranchise,
    deactivateFranchise,
    business,
  } = useBusinessContext();

  const [activeSubtab, setActiveSubtab] = useState("directory"); // 'directory' | 'analytics'
  const [search, setSearch] = useState("");
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [deactivateTarget, setDeactivateTarget] = useState(null);
  const [copiedId, setCopiedId] = useState(null);
  const [resentInviteId, setResentInviteId] = useState(null);

  // Role Protection Enforcement
  if (isFranchise) {
    return (
      <div className="bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 p-8 rounded-3xl text-center space-y-3">
        <ShieldAlert className="w-10 h-10 text-amber-600 mx-auto" />
        <h3 className="font-extrabold text-lg text-amber-900 dark:text-amber-200">
          Central Headquarters Access Required
        </h3>
        <p className="text-xs text-amber-700 dark:text-amber-300 max-w-md mx-auto">
          Multi-outlet franchise delegation, onboarding, and directory administration are managed exclusively from the central Headquarters (HQ) workspace.
        </p>
      </div>
    );
  }

  const activeOutletsCount = franchises.filter((f) => f.status === "Active").length;
  const pendingOutletsCount = franchises.filter((f) => f.status === "Pending Acceptance").length;

  const filteredFranchises = franchises.filter((f) => {
    const sTerm = search.toLowerCase();
    return (
      f.name.toLowerCase().includes(sTerm) ||
      f.city.toLowerCase().includes(sTerm) ||
      (f.adminName && f.adminName.toLowerCase().includes(sTerm)) ||
      (f.adminEmail && f.adminEmail.toLowerCase().includes(sTerm))
    );
  });

  const handleCopyInviteLink = (fr) => {
    const link = `https://thikana.inc/onboard?outlet=${fr.id}`;
    navigator.clipboard.writeText(link);
    setCopiedId(fr.id);
    toast.success(`Copied invite link for ${fr.name}`);
    setTimeout(() => setCopiedId(null), 2500);
  };

  const handleResendInvite = async (fr) => {
    try {
      setResentInviteId(fr.id);
      await fetch("/api/franchise/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: fr.adminEmail, name: fr.name }),
      }).catch((err) => console.log(err));

      toast.success(`Resent email invitation to ${fr.adminEmail}`);
      setTimeout(() => setResentInviteId(null), 2500);
    } catch (err) {
      toast.error("Failed to resend invite");
    }
  };

  const handleConfirmDeactivation = async () => {
    if (!deactivateTarget) return;

    try {
      await fetch("/api/franchise/delete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ franchiseId: deactivateTarget.id }),
      }).catch((err) => console.log(err));

      deactivateFranchise(deactivateTarget.id);
      toast.success(`Deactivated ${deactivateTarget.name}`);
      setDeactivateTarget(null);
    } catch (err) {
      toast.error("Error deactivating franchise");
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Sub-Navigation Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-white dark:bg-[#1A1A1A] p-5 rounded-3xl border border-[#E5E0D8] dark:border-white/10 shadow-xs">
        <div>
          <h2 className="text-xl font-black text-[#1A1A1A] dark:text-white flex items-center gap-2">
            <Building2 className="w-5 h-5 text-amber-500" /> Enterprise Multi-Franchise Command
          </h2>
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
            Oversee child outlets, analyze sales velocity, and switch workspace contexts.
          </p>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          {/* Subtab Toggle Buttons */}
          <div className="flex items-center gap-1 bg-[#F2EFE9] dark:bg-[#252525] p-1.5 rounded-2xl">
            <button
              onClick={() => setActiveSubtab("directory")}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition ${
                activeSubtab === "directory"
                  ? "bg-[#1A1A1A] text-white dark:bg-white dark:text-[#1A1A1A] shadow-xs"
                  : "text-gray-600 dark:text-gray-400 hover:text-black dark:hover:text-white"
              }`}
            >
              Outlets Directory ({franchises.length})
            </button>
            <button
              onClick={() => setActiveSubtab("analytics")}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition ${
                activeSubtab === "analytics"
                  ? "bg-[#1A1A1A] text-white dark:bg-white dark:text-[#1A1A1A] shadow-xs"
                  : "text-gray-600 dark:text-gray-400 hover:text-black dark:hover:text-white"
              }`}
            >
              Sales & Growth Analytics
            </button>
          </div>

          <button
            onClick={() => setIsAddModalOpen(true)}
            className="bg-amber-500 hover:bg-amber-600 text-white px-4 py-2.5 rounded-2xl text-xs font-bold transition flex items-center gap-1.5 shadow-md shrink-0"
          >
            <Plus className="w-4 h-4" /> Add New Franchise
          </button>
        </div>
      </div>

      {activeSubtab === "analytics" ? (
        <FranchiseAnalyticsView franchises={franchises} />
      ) : (
        /* Directory View */
        <div className="space-y-6 animate-in fade-in duration-200">
          {/* 4-Card KPI Summary Header */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-white dark:bg-[#1A1A1A] p-5 rounded-3xl border border-[#E5E0D8] dark:border-white/10 shadow-xs">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-gray-500">
                Total Franchises
              </span>
              <p className="text-2xl font-black text-[#1A1A1A] dark:text-white mt-1">
                {franchises.length} Outlets
              </p>
            </div>

            <div className="bg-white dark:bg-[#1A1A1A] p-5 rounded-3xl border border-emerald-200 dark:border-emerald-900/40 shadow-xs">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">
                Active Outlets
              </span>
              <p className="text-2xl font-black text-emerald-600 dark:text-emerald-400 mt-1">
                {activeOutletsCount} Active
              </p>
            </div>

            <div className="bg-white dark:bg-[#1A1A1A] p-5 rounded-3xl border border-amber-200 dark:border-amber-900/40 shadow-xs">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-amber-600 dark:text-amber-400">
                Pending Outlets
              </span>
              <p className="text-2xl font-black text-amber-600 dark:text-amber-400 mt-1">
                {pendingOutletsCount} Pending
              </p>
            </div>

            <div className="bg-white dark:bg-[#1A1A1A] p-5 rounded-3xl border border-[#E5E0D8] dark:border-white/10 shadow-xs">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-gray-500">
                HQ Organization Name
              </span>
              <p className="text-base font-black text-[#1A1A1A] dark:text-white truncate mt-1">
                {business?.name || "Thikana HQ Central"}
              </p>
            </div>
          </div>

          {/* Case-Insensitive Search Bar */}
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by outlet name, city, administrator name, or email..."
              className="w-full bg-white dark:bg-[#1A1A1A] border border-[#E5E0D8] dark:border-white/10 rounded-2xl py-3 pl-11 pr-4 text-xs sm:text-sm font-medium text-[#1A1A1A] dark:text-white outline-none focus:border-amber-500 transition shadow-xs"
            />
          </div>

          {/* Responsive Outlets Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {filteredFranchises.map((fr) => (
              <div
                key={fr.id}
                className="bg-white dark:bg-[#1A1A1A] border border-[#E5E0D8] dark:border-white/10 rounded-3xl p-6 shadow-xs hover:shadow-md transition-all duration-200 flex flex-col justify-between space-y-4"
              >
                <div>
                  {/* Card Header: Store Badge & Status */}
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-2xl bg-amber-100 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 flex items-center justify-center font-bold shrink-0">
                        <Store className="w-5 h-5" />
                      </div>
                      <div>
                        <h3 className="font-extrabold text-base text-[#1A1A1A] dark:text-white">
                          {fr.name}
                        </h3>
                        <p className="text-xs text-gray-500 flex items-center gap-1 mt-0.5">
                          <MapPin className="w-3.5 h-3.5 text-gray-400" /> {fr.address}, {fr.city}
                        </p>
                      </div>
                    </div>

                    <span
                      className={`px-2.5 py-1 rounded-full text-[10px] font-extrabold uppercase tracking-wide shrink-0 ${
                        fr.status === "Active"
                          ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300"
                          : "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300"
                      }`}
                    >
                      {fr.status === "Active" ? (
                        "Active Outlet"
                      ) : (
                        <span className="flex items-center gap-1">
                          <span className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-ping" /> Pending Acceptance
                        </span>
                      )}
                    </span>
                  </div>

                  {/* Administrator Preview Box */}
                  <div className="bg-gray-50 dark:bg-[#222] p-3.5 rounded-2xl border border-gray-100 dark:border-white/5 my-3 space-y-1 text-xs">
                    <span className="text-[10px] font-extrabold uppercase text-gray-400">
                      Franchise Administrator
                    </span>
                    <p className="font-bold text-[#1A1A1A] dark:text-white flex items-center gap-1.5">
                      <User className="w-3.5 h-3.5 text-amber-500" /> {fr.adminName || "Administrator"}
                    </p>
                    <p className="text-gray-500 flex items-center gap-1.5">
                      <Mail className="w-3.5 h-3.5 text-gray-400" /> {fr.adminEmail || "admin@thikana.inc"}
                    </p>
                    <p className="text-gray-500 flex items-center gap-1.5">
                      <Phone className="w-3.5 h-3.5 text-gray-400" /> {fr.phone || "+91 98000 00000"}
                    </p>
                  </div>
                </div>

                {/* Footer with 4 Interactive Controls */}
                <div className="pt-3 border-t border-gray-100 dark:border-white/10 flex flex-wrap items-center justify-between gap-2">
                  <div className="flex items-center gap-1.5">
                    <button
                      onClick={() => handleCopyInviteLink(fr)}
                      className="p-2 rounded-xl border border-gray-200 dark:border-white/10 hover:bg-gray-100 dark:hover:bg-white/10 text-gray-700 dark:text-gray-300 text-xs transition"
                      title="Copy Invite Link"
                    >
                      {copiedId === fr.id ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>

                    <button
                      onClick={() => handleResendInvite(fr)}
                      className="p-2 rounded-xl border border-gray-200 dark:border-white/10 hover:bg-gray-100 dark:hover:bg-white/10 text-gray-700 dark:text-gray-300 text-xs transition"
                      title="Resend Invitation Email"
                    >
                      <Send className="w-3.5 h-3.5" />
                    </button>

                    <button
                      onClick={() => setDeactivateTarget(fr)}
                      className="p-2 rounded-xl hover:bg-rose-50 text-rose-600 transition"
                      title="Remove / Deactivate Franchise"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>

                  <button
                    onClick={() => switchToFranchise(fr)}
                    className="bg-[#1A1A1A] text-white dark:bg-white dark:text-[#1A1A1A] hover:opacity-90 px-4 py-2 rounded-2xl text-xs font-bold transition flex items-center gap-1.5 shadow-xs"
                  >
                    Switch to Outlet <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Add New Franchise Modal */}
      <FranchiseModal
        isOpen={isAddModalOpen}
        onClose={() => setIsAddModalOpen(false)}
        onAddFranchise={(payload) => addFranchise(payload)}
      />

      {/* Shadcn-Style Confirmation AlertDialog for Deactivation */}
      {deactivateTarget && (
        <div className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4 backdrop-blur-xs">
          <div className="bg-white dark:bg-[#1C1C1C] rounded-3xl border border-[#E5E0D8] dark:border-white/10 p-6 w-full max-w-sm text-center shadow-2xl animate-in zoom-in-95 duration-150">
            <AlertTriangle className="w-10 h-10 text-rose-500 mx-auto mb-3" />
            <h3 className="font-extrabold text-base text-[#1A1A1A] dark:text-white">
              Remove {deactivateTarget.name}?
            </h3>
            <p className="text-xs text-gray-500 mt-1 mb-6">
              Deactivating this outlet will revoke scoped access for administrator {deactivateTarget.adminEmail}.
            </p>

            <div className="flex gap-3">
              <button
                onClick={() => setDeactivateTarget(null)}
                className="flex-1 py-2.5 rounded-2xl border border-gray-200 dark:border-white/10 text-xs font-bold text-gray-600 dark:text-gray-300"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmDeactivation}
                className="flex-1 py-2.5 rounded-2xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold transition shadow-xs"
              >
                Confirm Deactivate
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
